### ISSUE TITLE
Unwinable seed

### ISSUE THREAD

**Issue by Starvos** [gameboy9/DW2Randomizer#21]
Hello.
I'd just like to let you know that i encountered an unwinable seed. 1816752817 was the seed and when I got to Rhone the passage way to the end castle was blocked by sea. Just thought to let you know. 

Take care.

**Comment by gameboy9** [comment]
Yikes!  I'll take a look; thanks for letting me know!

**Comment by gameboy9** [comment]
I think this is happening because the mountains are being assessed as part of the same land mass but they should not be a part of any land mass because it's blocking your path.  I'll work on a fix.

**Comment by gameboy9** [comment]
OK, it should be fixed now.  Please reopen this issue if you happen to find another unwinnable seed.  Thanks again!
