### ISSUE TITLE
Unhandled Exception with Compare button

### ISSUE THREAD

**Issue by EvilAsh25** [gameboy9/DW2Randomizer#4]
If you hit the 'Compare' button before the Randomize button, it causes an Unhandled Exception.

**Comment by gameboy9** [comment]
Can you tell me what the exception said?  I've noticed there are at least two ways it can happen:  empty path in the ROM file, and file not found.  It could be another way though.  Thanks!

**Comment by EvilAsh25** [comment]
System.IO.FileNotFoundException: Could not find file 'C:\Users\EvilAsh\Desktop\DW2Randomizer\DW2Rando_1443274437.nes'.
File name: 'C:\Users\EvilAsh\Desktop\DW2Randomizer\DW2Rando_1443274437.nes'

It is because the file didn't exist yet, because I hadn't pressed the 'Randomize' button yet.

**Comment by gameboy9** [comment]
I think this is addressed, EvilAsh.  Please test, and, if you're good with it, close the issue.  Thanks!
