### ISSUE TITLE
Unhandled Exception with 'Browse' button

### ISSUE THREAD

**Issue by EvilAsh25** [gameboy9/DW2Randomizer#5]
When the program is first downloaded (only the .exe exists), the 'Rom Image Path' is blank (i.e. no lastFile.txt) the program throws an exception when the 'Browse' button is pressed. 

Workaround is to copy/paste in the path to the Rom file manually.

**Comment by gameboy9** [comment]
Ah, I think I see what's going on... it says could not find file "C:\whatever"... I bet it also was an "empty string" type of thing.  I think I just need to skip the error.  Thanks for the report; I'll get that all fixed up!

**Comment by gameboy9** [comment]
I think this is taken care of, EvilAsh.  Please test, and, if you're good with it, close the issue.  Thanks!
