### ISSUE TITLE
Feature Request: Include the Randomization Name in the Filename

### ISSUE THREAD

**Issue by EvilAsh25** [gameboy9/DW2Randomizer#7]
I like to make a bunch of randomized roms and copy them over to my flash card all at once, it would be nice to be able to distinguish between the different levels of randomization in the filename itself (i.e. Heavy, Insane, etc...).

**Comment by gameboy9** [comment]
This is a good idea, and it's implemented in full.  I also included the three checked options in the filename as well.  Please test and, if this is good with you, close this issue.  Thanks!
